#ifndef LWIP_LWIPOPTS_H
#define LWIP_LWIPOPTS_H

#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0

#define LWIP_SOCKET 0
#define LWIP_NETCONN 0

#define LWIP_ARP 1
#define LWIP_ETHERNET 1
#define LWIP_ICMP 1
#define LWIP_IPV4 1
#define LWIP_DHCP 0

#define LWIP_TCP 1
#define LWIP_UDP 0

#define MEM_ALIGNMENT 8
#define MEM_SIZE 65536
#define MEMP_NUM_PBUF 16
#define MEMP_NUM_UDP_PCB 4
#define MEMP_NUM_TCP_PCB 4
#define MEMP_NUM_TCP_PCB_LISTEN 4
#define MEMP_NUM_TCP_SEG 16
#define MEMP_NUM_SYS_TIMEOUT 4

#define PBUF_POOL_SIZE 16
#define PBUF_POOL_BUFSIZE 1536

#define LWIP_NETIF_LINK_CALLBACK 0
#define LWIP_NETIF_STATUS_CALLBACK 0
#define LWIP_NETIF_EXT_STATUS_CALLBACK 0

#define LWIP_RAND() 0x12345678

// Disable checksum generation for now to simplify
#define CHECKSUM_GEN_IP 1
#define CHECKSUM_GEN_ICMP 1
#define CHECKSUM_CHECK_IP 1
#define CHECKSUM_CHECK_ICMP 1

#endif // LWIP_LWIPOPTS_H
